"""
CEO Briefing Generator - Weekly Business Audit

Generates comprehensive "Monday Morning CEO Briefing" reports including:
- Revenue analysis
- Bottleneck identification
- Subscription audit
- Task completion metrics
- Social media engagement summary
- Accounting insights

Runs every Sunday night, generates briefing for the week.
"""

import json
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from collections import defaultdict

logger = logging.getLogger(__name__)


class CEOBriefingGenerator:
    """Generates weekly CEO briefing reports"""
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.logs_path = self.vault_path / "Logs"
        self.briefings_path = self.vault_path / "Briefings"
        self.accounting_path = self.vault_path / "Accounting"
        self.done_path = self.vault_path / "Done"
        
        # Ensure directories exist
        self.briefings_path.mkdir(parents=True, exist_ok=True)
    
    def generate_briefing(self, week_end: Optional[datetime] = None) -> str:
        """
        Generate complete CEO briefing for the week
        
        Args:
            week_end: End date of the week (defaults to last Sunday)
        """
        if week_end is None:
            # Default to last Sunday
            today = datetime.now()
            days_since_sunday = today.weekday() + 1 if today.weekday() < 6 else 0
            week_end = today - timedelta(days=days_since_sunday)
            week_end = week_end.replace(hour=23, minute=59, second=59)
        
        week_start = week_end - timedelta(days=6)
        week_start = week_start.replace(hour=0, minute=0, second=0)
        
        logger.info(f"Generating CEO briefing for {week_start.strftime('%Y-%m-%d')} to {week_end.strftime('%Y-%m-%d')}")
        
        # Gather all sections
        executive_summary = self._generate_executive_summary(week_start, week_end)
        revenue_section = self._generate_revenue_section(week_start, week_end)
        tasks_section = self._generate_tasks_section(week_start, week_end)
        bottlenecks_section = self._generate_bottlenecks_section(week_start, week_end)
        social_section = self._generate_social_section(week_start, week_end)
        accounting_section = self._generate_accounting_section(week_start, week_end)
        proactive_section = self._generate_proactive_suggestions(week_start, week_end)
        
        # Compile briefing
        briefing = f"""---
generated: {datetime.now().isoformat()}
period_start: {week_start.strftime('%Y-%m-%d')}
period_end: {week_end.strftime('%Y-%m-%d')}
type: ceo_briefing
---

# Monday Morning CEO Briefing

**Week:** {week_start.strftime('%B %d')} - {week_end.strftime('%B %d, %Y')}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

{executive_summary}

---

{revenue_section}

---

{tasks_section}

---

{bottlenecks_section}

---

{social_section}

---

{accounting_section}

---

{proactive_section}

---

*Generated by AI Employee v1.0 (Gold Tier)*
"""
        
        # Save briefing
        filename = f"CEO_Briefing_{week_end.strftime('%Y-%m-%d')}.md"
        briefing_file = self.briefings_path / filename
        briefing_file.write_text(briefing, encoding="utf-8")
        
        logger.info(f"CEO briefing saved to {briefing_file}")
        
        return briefing
    
    def _generate_executive_summary(self, week_start: datetime, week_end: datetime) -> str:
        """Generate executive summary with key metrics"""
        tasks_completed = self._count_tasks_completed(week_start, week_end)
        revenue = self._calculate_weekly_revenue(week_start, week_end)
        pending_items = self._count_pending_items()
        
        # Determine overall status
        if tasks_completed >= 10 and revenue > 0:
            status = "Strong week with solid progress"
        elif tasks_completed >= 5:
            status = "Moderate week with steady progress"
        else:
            status = "Light week, focus areas identified"
        
        summary = f"""## Executive Summary

{status}. 

**Key Highlights:**
- **Tasks Completed:** {tasks_completed}
- **Revenue This Week:** ${revenue:,.2f}
- **Pending Items:** {pending_items}
- **Overall Status:** {'🟢 On Track' if tasks_completed >= 10 else '🟡 Needs Attention' if tasks_completed >= 5 else '🔴 Behind'}
"""
        
        return summary
    
    def _generate_revenue_section(self, week_start: datetime, week_end: datetime) -> str:
        """Generate revenue analysis"""
        weekly_revenue = self._calculate_weekly_revenue(week_start, week_end)
        mtd_revenue = self._calculate_mtd_revenue()
        monthly_target = 10000  # From Business_Goals.md
        
        progress_pct = (mtd_revenue / monthly_target * 100) if monthly_target > 0 else 0
        
        # Calculate trend (compare to previous week)
        prev_week_start = week_start - timedelta(days=7)
        prev_week_end = week_start - timedelta(days=1)
        prev_week_revenue = self._calculate_weekly_revenue(prev_week_start, prev_week_end)
        
        if prev_week_revenue > 0:
            trend_pct = ((weekly_revenue - prev_week_revenue) / prev_week_revenue) * 100
            trend_str = f"{'↑' if trend_pct > 0 else '↓'} {abs(trend_pct):.1f}% vs last week"
        else:
            trend_str = "No previous week data"
        
        revenue_section = f"""## Revenue

### This Week
- **Weekly Revenue:** ${weekly_revenue:,.2f}
- **Month-to-Date:** ${mtd_revenue:,.2f}
- **Monthly Target:** ${monthly_target:,.2f}
- **Progress:** {progress_pct:.1f}%
- **Trend:** {trend_str}

### Status
{'🟢 Ahead of target' if progress_pct >= 50 else '🟡 On track' if progress_pct >= 25 else '🔴 Behind target'}
"""
        
        return revenue_section
    
    def _generate_tasks_section(self, week_start: datetime, week_end: datetime) -> str:
        """Generate completed tasks section"""
        tasks = self._get_tasks_completed(week_start, week_end)
        
        tasks_md = "### Completed Tasks This Week\n\n"
        
        if tasks:
            for task in sorted(tasks, key=lambda x: x.get("completed_at", ""), reverse=True):
                task_name = task.get("task_name", "Unknown Task")
                completed_at = task.get("completed_at", "")
                try:
                    completed_date = datetime.fromisoformat(completed_at).strftime("%b %d")
                except:
                    completed_date = "Unknown"
                
                tasks_md += f"- [x] {task_name} ({completed_date})\n"
        else:
            tasks_md += "No tasks completed this week.\n"
        
        tasks_md += f"\n**Total:** {len(tasks)} tasks completed\n"
        
        return tasks_md
    
    def _generate_bottlenecks_section(self, week_start: datetime, week_end: datetime) -> str:
        """Identify bottlenecks and delays"""
        bottlenecks = self._identify_bottlenecks(week_start, week_end)
        
        bottlenecks_md = """## Bottlenecks

"""
        
        if bottlenecks:
            bottlenecks_md += "| Task | Expected | Actual | Delay |\n"
            bottlenecks_md += "|------|----------|--------|-------|\n"
            
            for bn in bottlenecks:
                bottlenecks_md += f"| {bn['task']} | {bn['expected']} | {bn['actual']} | +{bn['delay']} |\n"
        else:
            bottlenecks_md += "No significant bottlenecks identified this week.\n"
        
        return bottlenecks_md
    
    def _generate_social_section(self, week_start: datetime, week_end: datetime) -> str:
        """Generate social media engagement summary"""
        social_files = list(self.briefings_path.glob("social_summary_*.md"))
        
        # Find most recent social summary
        latest_summary = None
        for sf in sorted(social_files, reverse=True):
            content = sf.read_text(encoding="utf-8")
            latest_summary = content
            break
        
        social_md = """## Social Media Activity

"""
        
        if latest_summary:
            # Extract key points (simplified)
            social_md += "Social media summary available. See full report: `Briefings/social_summary_*.md`\n\n"
            social_md += "**Key Actions This Week:**\n"
            social_md += "- Review social summary for engagement metrics\n"
            social_md += "- Check for unanswered messages or comments\n"
        else:
            social_md += "No social media activity tracked this week.\n"
            social_md += "\n**Recommendation:** Set up Facebook/Instagram watchers to monitor engagement.\n"
        
        return social_md
    
    def _generate_accounting_section(self, week_start: datetime, week_end: datetime) -> str:
        """Generate accounting insights"""
        # Look for accounting files
        accounting_files = list(self.accounting_path.glob("*.md"))
        
        accounting_md = """## Accounting & Finance

"""
        
        if accounting_files:
            accounting_md += "**Recent Accounting Files:**\n\n"
            for af in sorted(accounting_files)[-5:]:
                accounting_md += f"- `{af.name}`\n"
            
            accounting_md += "\n**Action Items:**\n"
            accounting_md += "- Review latest financial summary\n"
            accounting_md += "- Check outstanding invoices\n"
            accounting_md += "- Verify payment collections\n"
        else:
            accounting_md += "No accounting data available this week.\n"
            accounting_md += "\n**Recommendation:** Set up Odoo integration for automated accounting.\n"
        
        return accounting_md
    
    def _generate_proactive_suggestions(self, week_start: datetime, week_end: datetime) -> str:
        """Generate proactive suggestions and optimizations"""
        suggestions = self._analyze_for_suggestions(week_start, week_end)
        
        suggestions_md = """## Proactive Suggestions

"""
        
        if suggestions.get("cost_optimizations"):
            suggestions_md += "### Cost Optimization\n\n"
            for opt in suggestions["cost_optimizations"]:
                suggestions_md += f"- **{opt['item']}**: {opt['detail']}\n"
                suggestions_md += f"  - [ACTION] {opt['action']} Move to /Pending_Approval\n\n"
        
        if suggestions.get("upcoming_deadlines"):
            suggestions_md += "### Upcoming Deadlines\n\n"
            for deadline in suggestions["upcoming_deadlines"]:
                suggestions_md += f"- **{deadline['task']}**: {deadline['date']} ({deadline['days_left']} days)\n"
        
        if suggestions.get("recommendations"):
            suggestions_md += "\n### Recommendations\n\n"
            for rec in suggestions["recommendations"]:
                suggestions_md += f"- {rec}\n"
        
        return suggestions_md
    
    # Helper methods for data gathering
    
    def _count_tasks_completed(self, week_start: datetime, week_end: datetime) -> int:
        """Count tasks completed in the week"""
        tasks = self._get_tasks_completed(week_start, week_end)
        return len(tasks)
    
    def _get_tasks_completed(self, week_start: datetime, week_end: datetime) -> List[Dict]:
        """Get list of tasks completed in date range"""
        tasks = []
        
        if not self.done_path.exists():
            return tasks
        
        # Scan Done folder for completed tasks
        for task_file in self.done_path.rglob("*.md"):
            try:
                content = task_file.read_text(encoding="utf-8")
                
                # Look for completed timestamp in frontmatter or content
                if "completed:" in content or "status: done" in content.lower():
                    # Simple extraction (in production, parse YAML frontmatter)
                    tasks.append({
                        "task_name": task_file.stem,
                        "completed_at": datetime.now().isoformat(),
                        "file": str(task_file),
                    })
            except Exception as e:
                logger.debug(f"Error reading task file {task_file}: {e}")
        
        # Also check logs for completed actions
        if self.logs_path.exists():
            for log_file in self.logs_path.glob("*.jsonl"):
                try:
                    with open(log_file, "r", encoding="utf-8") as f:
                        for line in f:
                            try:
                                entry = json.loads(line.strip())
                                entry_time = datetime.fromisoformat(entry.get("timestamp", ""))
                                
                                if week_start <= entry_time <= week_end:
                                    if entry.get("result") == "success":
                                        tasks.append({
                                            "task_name": entry.get("action", "Unknown"),
                                            "completed_at": entry.get("timestamp"),
                                        })
                            except:
                                continue
                except Exception as e:
                    logger.debug(f"Error reading log file {log_file}: {e}")
        
        return tasks
    
    def _calculate_weekly_revenue(self, week_start: datetime, week_end: datetime) -> float:
        """Calculate revenue for the week"""
        revenue = 0.0
        
        # Check accounting files for transactions
        if self.accounting_path.exists():
            for acct_file in self.accounting_path.glob("*.md"):
                try:
                    content = acct_file.read_text(encoding="utf-8")
                    # Simple parsing - look for dollar amounts
                    import re
                    amounts = re.findall(r'\$?([\d,]+\.?\d*)', content)
                    for amt in amounts:
                        try:
                            revenue += float(amt.replace(",", ""))
                        except:
                            pass
                except:
                    pass
        
        return revenue
    
    def _calculate_mtd_revenue(self) -> float:
        """Calculate month-to-date revenue"""
        first_of_month = datetime.now().replace(day=1, hour=0, minute=0, second=0)
        return self._calculate_weekly_revenue(first_of_month, datetime.now())
    
    def _count_pending_items(self) -> int:
        """Count items pending action"""
        pending_count = 0
        
        pending_path = self.vault_path / "Pending_Approval"
        if pending_path.exists():
            pending_count += len(list(pending_path.glob("*.md")))
        
        needs_action_path = self.vault_path / "Needs_Action"
        if needs_action_path.exists():
            pending_count += len(list(needs_action_path.glob("*.md")))
        
        return pending_count
    
    def _identify_bottlenecks(self, week_start: datetime, week_end: datetime) -> List[Dict]:
        """Identify tasks that took longer than expected"""
        bottlenecks = []
        
        # Analyze Plans folder for delayed tasks
        plans_path = self.vault_path / "Plans"
        if plans_path.exists():
            for plan_file in plans_path.glob("*.md"):
                try:
                    content = plan_file.read_text(encoding="utf-8")
                    
                    # Look for delays (simplified logic)
                    if "delay" in content.lower() or "behind" in content.lower():
                        bottlenecks.append({
                            "task": plan_file.stem,
                            "expected": "2 days",
                            "actual": "5 days",
                            "delay": "3 days",
                        })
                except:
                    pass
        
        return bottlenecks
    
    def _analyze_for_suggestions(self, week_start: datetime, week_end: datetime) -> Dict:
        """Analyze data for proactive suggestions"""
        suggestions = {
            "cost_optimizations": [],
            "upcoming_deadlines": [],
            "recommendations": [],
        }
        
        # Check for unused subscriptions (from Business_Goals.md rules)
        business_goals = self.vault_path / "Business_Goals.md"
        if business_goals.exists():
            content = business_goals.read_text(encoding="utf-8")
            if "subscription" in content.lower():
                suggestions["cost_optimizations"].append({
                    "item": "Software Subscriptions",
                    "detail": "Review inactive subscriptions",
                    "action": "Audit and cancel unused services?",
                })
        
        # Upcoming deadlines from Plans
        plans_path = self.vault_path / "Plans"
        if plans_path.exists():
            for plan_file in plans_path.glob("*.md"):
                try:
                    content = plan_file.read_text(encoding="utf-8")
                    if "due:" in content.lower() or "deadline:" in content.lower():
                        suggestions["upcoming_deadlines"].append({
                            "task": plan_file.stem,
                            "date": "Check plan file",
                            "days_left": 7,
                        })
                except:
                    pass
        
        # General recommendations
        pending_count = self._count_pending_items()
        if pending_count > 10:
            suggestions["recommendations"].append(
                f"High number of pending items ({pending_count}). Consider prioritizing or delegating."
            )
        
        return suggestions


if __name__ == "__main__":
    import sys
    
    vault_path = sys.argv[1] if len(sys.argv) > 1 else "./AI_Employee_Vault"
    
    generator = CEOBriefingGenerator(vault_path)
    briefing = generator.generate_briefing()
    
    print("\n" + "=" * 80)
    print("CEO BRIEFING GENERATED")
    print("=" * 80)
    print(briefing)
